env:
  browser: true
  es2022: true

extends:
  - airbnb
  - plugin:react/recommended
  - plugin:import/recommended
  - plugin:react-hooks/recommended

parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: latest
  sourceType: module

plugins:
  - react
  - import

rules:
  semi: ["error", "always"]
  indent: ["error", 2]
  no-console: 0
  import/extensions: 0
  import/no-unresolved: 0
  import/order: 0
  react/prop-types: 0
  react/jsx-indent: ["error", 2]
  react/jsx-indent-props: ["error", 2]
  react/react-in-jsx-scope: 0
  no-restricted-exports: ["error", { "restrictedNamedExports": ["defaultFrom", "index"] }]
  max-len: ["error", { "code": 100, "ignoreStrings": true }]
  no-underscore-dangle: [2, { "allow": ["__filename", "__dirname"] }]
  no-param-reassign: ["error", { "props": false }]
  react/function-component-definition: [2, { "namedComponents": "arrow-function" }]
  testing-library/no-debug: 0
  react/jsx-filename-extension: [1, { "extensions": [".jsx", ".js"] }]